### ISSUE TITLE
Add support for white letters

### ISSUE THREAD

**Issue by codesome** [rfratto/alphabet-echo#1]
![Screenshot from 2020-12-17 16-01-57](https://user-images.githubusercontent.com/15064823/102476574-47883600-4081-11eb-8622-31542ca4dc0b.png)

**Comment by rfratto** [comment]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/630212/102489954-310bbb80-403c-11eb-8d65-f35f5af41cd9.png">

**Comment by codesome** [comment]
![Screenshot from 2020-12-21 17-31-15](https://user-images.githubusercontent.com/15064823/102775194-66a10380-43b2-11eb-9eb8-274f1e3d1e3f.png)
